openapi: "3.1.0"
info:
  version: 1.0.0
  title: PersonaJr, PersonaInt, and PersonaSr API
  license:
    name: MIT
servers:
  - url: addyoururlhere.com/agents
paths:
  /personaJr:
    post:
      summary: Interact with personaJr agent
      operationId: askPersonaJr
      tags:
        - personaJr
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonaJrResponse"
  /personaInt:
    post:
      summary: Interact with personaInt agent
      operationId: askPersonaInt
      tags:
        - personaInt
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonaIntResponse"
  /personaSr:
    post:
      summary: Interact with personaSr agent
      operationId: askPersonaSr
      tags:
        - personaSr
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                input:
                  type: string
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PersonaSrResponse"
components:
  schemas:
    PersonaJrResponse:
      type: object
      properties:
        output:
          type: string
    PersonaIntResponse:
      type: object
      properties:
        output:
          type: string
    PersonaSrResponse:
      type: object
      properties:
        output:
          type: string
